MY_CONFIG_ROOT="$HOME/MyConfigurations"

# fpath changes must come before compinit
fpath=($MY_CONFIG_ROOT/zsh/zsh-completions/src $fpath)

# Import configurations
source "$MY_CONFIG_ROOT/common/common.zsh"
source "$MY_CONFIG_ROOT/lib/clipboard.zsh"
source "$MY_CONFIG_ROOT/lib/completion.zsh"
source "$MY_CONFIG_ROOT/lib/correction.zsh"
source "$MY_CONFIG_ROOT/lib/directories.zsh"
source "$MY_CONFIG_ROOT/lib/history.zsh"
source "$MY_CONFIG_ROOT/lib/key-bindings.zsh"

if (( $+commands[kubectl] )); then
  source "$MY_CONFIG_ROOT/kubectl/kubectl.zsh"
fi

# Machine specific configurations
source "$HOME/.zshrc.local"

# Auto suggestions and syntax highlighting, needs to be always the last lines
source "$MY_CONFIG_ROOT/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"
source "$MY_CONFIG_ROOT/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
